### ISSUE TITLE
moving the blocks lat/long/ after rendering?

### ISSUE THREAD

**Issue by Orbyt** [askmike/realtime-webgl-globe#1]
How would you move the blocks to a new position smoothly in real time?

**Comment by askmike** [comment]
That functionality is currently not in the globe, but it is really easy to add. Here is a [quick example](https://gist.github.com/askmike/bced74328cb736de548d) ([live version here](http://mikevanrossum.nl/stuff/realtime-webgl-globe-moving/example.html)). Note that the example relies on one small difference in globe.js. Replace line 520 from:

```
 return this;
```

to:

```
 // return this;
return block; // return the block instead
```

The example is hacky: To only show you the moving block code I put it in an external HTML file. The best way would be to integrate this and expose methods for moving blocks around. There are comments in the code that should explain how it works!

**Comment by askmike** [comment]
Adding this functionality is not hard (see above example), but I won't have time for this. If anyone does, please send a PR.
